# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.b7 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.button("7"))
        self.b7.setGeometry(QtCore.QRect(20, 100, 61, 61))
        self.b7.setObjectName("b7")

        self.b8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("8"))
        self.b8.setGeometry(QtCore.QRect(90, 100, 61, 61))
        self.b8.setObjectName("b8")

        self.b9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("9"))
        self.b9.setGeometry(QtCore.QRect(160, 100, 61, 61))
        self.b9.setObjectName("b9")

        self.b4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("4"))
        self.b4.setGeometry(QtCore.QRect(20, 170, 61, 61))
        self.b4.setObjectName("b4")

        self.b5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("5"))
        self.b5.setGeometry(QtCore.QRect(90, 170, 61, 61))
        self.b5.setObjectName("b5")

        self.b6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("6"))
        self.b6.setGeometry(QtCore.QRect(160, 170, 61, 61))
        self.b6.setObjectName("b6")

        self.b1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("1"))
        self.b1.setGeometry(QtCore.QRect(20, 240, 61, 61))
        self.b1.setObjectName("b1")

        self.b2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("2"))
        self.b2.setGeometry(QtCore.QRect(90, 240, 61, 61))
        self.b2.setObjectName("b2")

        self.b3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("3"))
        self.b3.setGeometry(QtCore.QRect(160, 240, 61, 61))
        self.b3.setObjectName("b3")

        self.b0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("0"))
        self.b0.setGeometry(QtCore.QRect(20, 310, 131, 61))
        self.b0.setObjectName("b0")

        self.be = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("e"))
        self.be.setGeometry(QtCore.QRect(230, 310, 131, 61))
        self.be.setObjectName("be")
        
        self.bdel = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("del"))
        self.bdel.setGeometry(QtCore.QRect(230, 100, 61, 61))
        self.bdel.setObjectName("bdel")

        self.bac = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("ac"))
        self.bac.setGeometry(QtCore.QRect(300, 100, 61, 61))
        self.bac.setObjectName("bac")

        self.bmult = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("*"))
        self.bmult.setGeometry(QtCore.QRect(230, 170, 61, 61))
        self.bmult.setObjectName("bmult")

        self.bplus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("+"))
        self.bplus.setGeometry(QtCore.QRect(230, 240, 61, 61))
        self.bplus.setObjectName("bplus")

        self.bdiv = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("/"))
        self.bdiv.setGeometry(QtCore.QRect(300, 170, 61, 61))
        self.bdiv.setObjectName("bdiv")

        self.bmin = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("-"))
        self.bmin.setGeometry(QtCore.QRect(300, 240, 61, 61))
        self.bmin.setObjectName("bmin")

        self.bdec = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button("."))
        self.bdec.setGeometry(QtCore.QRect(160, 310, 61, 61))
        self.bdec.setObjectName("bdec")


        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(30, 20, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.output.setFont(font)
        self.output.setAutoFillBackground(True)
        self.output.setText("")

        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def button(self, uinput): 
        if self.output.text() == "ERR":
            self.output.setText("")
        
        if uinput == "del" and self.output.text() != "0":
            self.output.setText(self.output.text()[:-1])

        elif uinput == "ac":
            self.output.setText("")

        elif uinput == "e":
            try:
                self.output.setText(str(eval(self.output.text())))
            except:
                self.output.setText("ERR")
        else:
            self.output.setText(f'{self.output.text()}{uinput}')
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.be.setText(_translate("MainWindow", "="))
        self.bdel.setText(_translate("MainWindow", "DEL"))
        self.bac.setText(_translate("MainWindow", "AC"))
        self.bmult.setText(_translate("MainWindow", "*"))
        self.bplus.setText(_translate("MainWindow", "+"))
        self.bdiv.setText(_translate("MainWindow", "/"))
        self.bmin.setText(_translate("MainWindow", "-"))
        self.bdec.setText(_translate("MainWindow", "."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
