# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TODOLIST.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.taskView = QtWidgets.QListWidget(self.centralwidget)
        self.taskView.setGeometry(QtCore.QRect(30, 100, 711, 411))
        self.taskView.setObjectName("taskView")
        
        self.AddTask = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.adder())
        self.AddTask.setGeometry(QtCore.QRect(30, 50, 111, 31))
        self.AddTask.setObjectName("AddTask")

        self.RemoveTask = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.remover())
        self.RemoveTask.setGeometry(QtCore.QRect(160, 50, 111, 31))
        self.RemoveTask.setObjectName("RemoveTask")

        self.Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(30, 20, 241, 25))
        self.Input.setObjectName("Input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddTask.setText(_translate("MainWindow", "Add Task"))
        self.RemoveTask.setText(_translate("MainWindow", "Remove Task"))
        self.Input.setText(_translate("MainWindow", "Enter your task here!"))


    def adder(self):
        uinput = self.Input.text()

        self.taskView.addItem(uinput)
        self.Input.setText("")

    def remover(self):
        selected = self.taskView.currentRow()
        self.taskView.takeItem(selected)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
